name: Deploy SQL to Azure

on:
  push:
    branches:
      - master  # 또는 main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy SQL script to Azure
        uses: azure/sql-action@v1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONN }}
          path: ./sql-scripts/init.sql
