name: Deploy SQL script to Azure SQL

on:
  push:
    branches: [master]  # 또는 main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SQL Script
        uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONN }}
          script-path: ./sql-scripts/init.sql
